# To add a file that needs to be compiled, do all the steps marked by (*)

name: Github Actions CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3

      # (*) To add a file, add the following section for it
    - name: Compile natural language processing summary
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        working_directory: natural_language_processing

    - name: Compile computer vision summary
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        working_directory: computer_vision

      # (*) To add a file, add the PDF filename to the following
    - name: Check PDF files
      run: |
        file natural_language_processing/main.pdf | grep -q ' PDF '
        file computer_vision/main.pdf | grep -q ' PDF '

    - name: Upload to GitHub pages
      run: |
        git config --global user.name "Cristian Perez Jensen"
        git config --global user.email "cristianpjensen@gmail.com"

        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

        git clone --depth=1 --branch gh-pages git@github.com:cristianpjensen/eth-cs-notes.git "$GITHUB_WORKSPACE/deploy"

        # (*) To add a file, add the following command for that file
        cp -f natural_language_processing/main.pdf "$GITHUB_WORKSPACE/deploy/natural_language_processing-summary.pdf"
        cp -f computer_vision/main.pdf "$GITHUB_WORKSPACE/deploy/computer_vision-summary.pdf"

        cd "$GITHUB_WORKSPACE/deploy"

        # (*) To add a file, add it to the branch
        git add natural_language_processing-summary.pdf
        git add computer_vision-summary.pdf

        git commit -m "[github actions] deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
