# To add a file that needs to be compiled, do all the steps marked by (*)

name: Github Actions CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3

      # (*) To add a file, add the following section for it
    - name: Natural Language Processing (summary)
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        working_directory: natural_language_processing/summary

    - name: Natural Language Processing (cheatsheet)
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        working_directory: natural_language_processing/cheatsheet

    - name: Computer Vision (summary)
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        working_directory: computer_vision/summary

    - name: Probabilistic Artificial Intelligence (summary)
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        latexmk_shell_escape: true
        working_directory: probabilistic_artificial_intelligence/summary

    - name: Probabilistic Artificial Intelligence (cheatsheet)
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        working_directory: probabilistic_artificial_intelligence/cheatsheet

    - name: Algorithms Lab (summary)
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        working_directory: algorithms_lab/summary

    - name: Optimization for Data Science (summary)
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        latexmk_shell_escape: true
        working_directory: optimization_for_data_science/summary

    - name: Optimization for Data Science (cheatsheet)
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        working_directory: optimization_for_data_science/cheatsheet

    - name: Machine Perception (summary)
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        working_directory: machine_perception/summary

    - name: Machine Perception (cheatsheet)
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        working_directory: machine_perception/cheatsheet

    - name: Computational Intelligence Lab (summary)
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        working_directory: computational_intelligence_lab/summary

    - name: Advanced Machine Learning (summary)
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        working_directory: advanced_machine_learning/summary

    - name: Deep Learning (summary)
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        working_directory: deep_learning/summary

      # (*) To add a file, add the PDF filename to the following
    - name: Check PDF files
      run: |
        file natural_language_processing/summary/main.pdf | grep -q ' PDF '
        file natural_language_processing/cheatsheet/main.pdf | grep -q ' PDF '
        file computer_vision/summary/main.pdf | grep -q ' PDF '
        file probabilistic_artificial_intelligence/summary/main.pdf | grep -q ' PDF '
        file probabilistic_artificial_intelligence/cheatsheet/main.pdf | grep -q ' PDF '
        file algorithms_lab/summary/main.pdf | grep -q ' PDF '
        file optimization_for_data_science/summary/main.pdf | grep -q ' PDF '
        file optimization_for_data_science/cheatsheet/main.pdf | grep -q ' PDF '
        file machine_perception/summary/main.pdf | grep -q ' PDF '
        file machine_perception/cheatsheet/main.pdf | grep -q ' PDF '
        file computational_intelligence_lab/summary/main.pdf | grep -q ' PDF '
        file advanced_machine_learning/summary/main.pdf | grep -q ' PDF '
        file deep_learning/summary/main.pdf | grep -q ' PDF '

    - name: Upload to GitHub pages
      run: |
        git config --global user.name "Cristian Perez Jensen (auto)"
        git config --global user.email "cristianpjensen@gmail.com"

        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

        git clone --depth=1 --branch gh-pages git@github.com:cristianpjensen/eth-cs-notes.git "$GITHUB_WORKSPACE/deploy"

        # (*) To add a file, add the following command for that file
        cp -f natural_language_processing/summary/main.pdf "$GITHUB_WORKSPACE/deploy/natural_language_processing/summary.pdf"
        cp -f natural_language_processing/cheatsheet/main.pdf "$GITHUB_WORKSPACE/deploy/natural_language_processing/cheatsheet.pdf"
        cp -f computer_vision/summary/main.pdf "$GITHUB_WORKSPACE/deploy/computer_vision/summary.pdf"
        cp -f probabilistic_artificial_intelligence/summary/main.pdf "$GITHUB_WORKSPACE/deploy/probabilistic_artificial_intelligence/summary.pdf"
        cp -f probabilistic_artificial_intelligence/cheatsheet/main.pdf "$GITHUB_WORKSPACE/deploy/probabilistic_artificial_intelligence/cheatsheet.pdf"
        cp -f algorithms_lab/summary/main.pdf "$GITHUB_WORKSPACE/deploy/algorithms_lab/summary.pdf"
        cp -f optimization_for_data_science/summary/main.pdf "$GITHUB_WORKSPACE/deploy/optimization_for_data_science/summary.pdf"
        cp -f optimization_for_data_science/cheatsheet/main.pdf "$GITHUB_WORKSPACE/deploy/optimization_for_data_science/cheatsheet.pdf"
        cp -f machine_perception/summary/main.pdf "$GITHUB_WORKSPACE/deploy/machine_perception/summary.pdf"
        cp -f machine_perception/cheatsheet/main.pdf "$GITHUB_WORKSPACE/deploy/machine_perception/cheatsheet.pdf"
        cp -f computational_intelligence_lab/summary/main.pdf "$GITHUB_WORKSPACE/deploy/computational_intelligence_lab/summary.pdf"
        cp -f advanced_machine_learning/summary/main.pdf "$GITHUB_WORKSPACE/deploy/advanced_machine_learning/summary.pdf"
        cp -f deep_learning/summary/main.pdf "$GITHUB_WORKSPACE/deploy/deep_learning/summary.pdf"

        cd "$GITHUB_WORKSPACE/deploy"

        git add -A
        git commit -m "[github actions] deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
